using Microsoft.Extensions.AI;
using OneCode.Core.Errors;
using OneCode.Infrastructure.Agent;

namespace OneCode.App.Services.Agent;

/// <summary>
/// Branch agent running parameters.
/// </summary>
public sealed class ForkedAgentParams
{
    /// <summary>Prompt messages (input for the child agent).</summary>
    public IReadOnlyList<ChatMessage>? PromptMessages { get; init; }

    /// <summary>Parent agent context (for cache sharing and state isolation).</summary>
    public string? ParentWorkingDirectory { get; init; }

    /// <summary>Fork context messages (prepended to the message list).</summary>
    public IReadOnlyList<ChatMessage>? ForkContextMessages { get; init; }

    /// <summary>Tools the child agent is allowed to use (null = all tools).</summary>
    public IReadOnlyList<string>? AllowedTools { get; init; }

    /// <summary>Parent/child intersected immutable capability boundary.</summary>
    public ToolCapabilitySet? Capabilities { get; init; }

    /// <summary>Forked agent label (for logging and telemetry).</summary>
    public string? ForkLabel { get; init; }

    /// <summary>Maximum output tokens.</summary>
    public int? MaxOutputTokens { get; init; }

    /// <summary>Maximum turns (default 10).</summary>
    public int? MaxTurns { get; init; }

    /// <summary>Whether to skip transcript recording.</summary>
    public bool SkipTranscript { get; init; }

    /// <summary>Whether to skip cache write.</summary>
    public bool SkipCacheWrite { get; init; }

    /// <summary>Parent's cache-safe parameters for prompt cache sharing.</summary>
    public CacheSafeParams? CacheSafeParams { get; init; }

    /// <summary>Parent conversation ID for per-session cost tracking.</summary>
    public SessionId? ConversationId { get; init; }

    /// <summary>Pipeline profile controlling middleware trimming and tool filtering.</summary>
    public PipelineProfile Profile { get; init; } = PipelineProfile.Worker;
}

/// <summary>
/// Branch agent execution result.
/// </summary>
public sealed class ForkedAgentResult
{
    /// <summary>Final text output from the agent (via MAF AgentResponse.Text).</summary>
    public string? Text { get; init; }

    /// <summary>Messages generated by the child agent.</summary>
    public IReadOnlyList<ChatMessage> Messages { get; init; } = Array.Empty<ChatMessage>();

    /// <summary>Total input tokens consumed.</summary>
    public long TotalInputTokens { get; init; }

    /// <summary>Total output tokens consumed.</summary>
    public long TotalOutputTokens { get; init; }

    /// <summary>Number of turns executed.</summary>
    public int TurnCount { get; init; }

    /// <summary>Structured error details when the forked agent fails (ERR-1.4).</summary>
    public AgentProblemDetails? Error { get; init; }
}

