using Microsoft.Extensions.AI;
using OneCode.Core.Errors;
using OneCode.Infrastructure.Agent;

namespace OneCode.App.Services.Agent;

/// <summary>
/// Branch agent running parameters.
/// </summary>
public sealed class ForkedAgentParams
{
    /// <summary>Prompt messages (input for the child agent).</summary>
    public IReadOnlyList<ChatMessage>? PromptMessages { get; init; }

    /// <summary>Parent agent context (for cache sharing and state isolation).</summary>
    public string? ParentWorkingDirectory { get; init; }

    /// <summary>
    /// Fork 自身的角色正文（角色 overlay + 记忆检索提示），交给 MAF 作为
    /// <c>ChatOptions.Instructions</c>；harness 片段由 MAF 拼在它前面。Worker 等无角色
    /// overlay 的路径为 null，此时子 Agent 只保留 harness 片段 + 继承的父级 cache-safe system prompt。
    /// </summary>
    public string? AgentInstructions { get; init; }

    /// <summary>
    /// Shared harness fragment (<c>system/harness</c>) for the child agent, handed to MAF as
    /// <c>HarnessInstructions</c>. Set on every fork path — the fragment is never pre-joined into
    /// <see cref="AgentInstructions"/>, because MAF owns the composition order. Null only for callers
    /// that deliberately want MAF's default instructions instead.
    /// </summary>
    public string? HarnessInstructions { get; init; }

    /// <summary>Tools the child agent is allowed to use (null = all tools).</summary>
    public IReadOnlyList<string>? AllowedTools { get; init; }

    /// <summary>Parent/child intersected immutable capability boundary.</summary>
    public ToolCapabilitySet? Capabilities { get; init; }

    /// <summary>Forked agent label (for logging and telemetry).</summary>
    public string? ForkLabel { get; init; }

    /// <summary>Maximum output tokens.</summary>
    public int? MaxOutputTokens { get; init; }

    /// <summary>Maximum turns (default 10).</summary>
    public int? MaxTurns { get; init; }

    /// <summary>Whether to skip transcript recording.</summary>
    public bool SkipTranscript { get; init; }

    /// <summary>Whether to skip cache write.</summary>
    public bool SkipCacheWrite { get; init; }

    /// <summary>Parent's cache-safe parameters for prompt cache sharing.</summary>
    public CacheSafeParams? CacheSafeParams { get; init; }

    /// <summary>Parent conversation ID for per-session cost tracking.</summary>
    public SessionId? ConversationId { get; init; }

    /// <summary>Pipeline profile controlling middleware trimming and tool filtering.</summary>
    public PipelineProfile Profile { get; init; } = PipelineProfile.Worker;
}

/// <summary>
/// Branch agent execution result.
/// </summary>
public sealed class ForkedAgentResult
{
    /// <summary>Final text output from the agent (via MAF AgentResponse.Text).</summary>
    public string? Text { get; init; }

    /// <summary>Messages generated by the child agent.</summary>
    public IReadOnlyList<ChatMessage> Messages { get; init; } = [];

    /// <summary>Total input tokens consumed.</summary>
    public long TotalInputTokens { get; init; }

    /// <summary>Total output tokens consumed.</summary>
    public long TotalOutputTokens { get; init; }

    /// <summary>Number of turns executed.</summary>
    public int TurnCount { get; init; }

    /// <summary>Structured error details when the forked agent fails (ERR-1.4).</summary>
    public AgentProblemDetails? Error { get; init; }
}

