<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>OneCode.Cli</AssemblyName>
    <RootNamespace>OneCode.Cli</RootNamespace>
    <StartupObject></StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\OneCode.App\OneCode.App.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="OneCode.Tests" />
  </ItemGroup>

</Project>
