using OneCode.Tests.TestSupport;

if (args.Length > 0 && args[0] == "--probe")
    return await WorkflowRecoveryProbe.RunAsync(args[1..]).ConfigureAwait(false);

// All other invocations (dotnet test / xUnit.net v3 runner control protocol) are
// delegated to the xUnit auto-generated entry point. This keeps Program.Main as the
// assembly entry point so the "--probe" child processes work, while still letting the
// test host protocol (MTP --server / ConsoleRunner) dispatch correctly under `dotnet test`.
return OneCode.Tests.AutoGenerated.XunitAutoGeneratedEntryPoint.Main(args);
